# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=64, null=True)),
                ('city', models.CharField(max_length=25, null=True)),
                ('post_code', models.CharField(max_length=8)),
                ('county', models.CharField(max_length=25, null=True)),
                ('district', models.CharField(max_length=25, null=True)),
                ('city_district', models.CharField(max_length=25, null=True)),
                ('country', models.CharField(max_length=25, null=True)),
                ('primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deletion_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=64)),
                ('contact_section', models.CharField(choices=[('PHONE', 'Phone'), ('FAX', 'Fax'), ('EMAIL', 'Email'), ('WWW', 'www'), ('SKYPE', 'Skype'), ('SKYPE_NO', 'Skype_no'), ('BLOG', 'Blog'), ('OTHER', 'Other')], default='OTHER', max_length=15)),
                ('contact_type', models.CharField(choices=[('HOME', 'Home'), ('OFFICE', 'Offcice'), ('MOBILE', 'Mobile'), ('VOICE', 'Voice')], max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deletion_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.UUIDField()),
                ('email_sent', models.BooleanField(default=False)),
                ('mail_type', models.CharField(choices=[('ACTIVATION', 'Activation'), ('PASSWORD', 'Password')], default='ACTIVATION', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deletion_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.BigIntegerField(blank=True)),
                ('user_id_old', models.PositiveIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('is_cloud_admin', models.BooleanField(default=False)),
                ('admin_type', models.CharField(choices=[('CA', 'Cloud Admin'), ('AO', 'Application Owner'), ('RU', 'Regular User')], default='RU', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='graph',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iupdsmanager.Profile'),
        ),
        migrations.AddField(
            model_name='contact',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iupdsmanager.Profile'),
        ),
        migrations.AddField(
            model_name='address',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iupdsmanager.Profile'),
        ),
    ]
