# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.UUIDField()),
                ('email_sent', models.SmallIntegerField(default=0)),
                ('mail_type', models.CharField(choices=[('ACTIVATION', 'Freshman'), ('PASSWORD', 'Password')], default='ACTIVATION', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField()),
                ('is_cloud_admin', models.BooleanField(default=False)),
                ('admin_type', models.CharField(choices=[('CA', 'Cloud Admin'), ('AO', 'Application Owner'), ('RU', 'Regular User')], default='RU', max_length=15)),
            ],
        ),
    ]
