# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iupdsmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=64)),
                ('contact_type', models.CharField(choices=[('PHONE', 'Phone'), ('FAX', 'Fax'), ('EMAIL', 'Email'), ('WWW', 'www'), ('SKYPE', 'Skype'), ('SKYPE_NO', 'Skype_no'), ('BLOG', 'Blog'), ('OTHER', 'Other')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='emailtrack',
            name='mail_type',
            field=models.CharField(choices=[('ACTIVATION', 'Activation'), ('PASSWORD', 'Password')], default='ACTIVATION', max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='admin_type',
            field=models.CharField(choices=[('CA', 'Cloud Admin'), ('AO', 'Application Owner'), ('RU', 'Regular User')], default='RU', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iupdsmanager.Profile'),
        ),
    ]
