# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iupdsmanager', '0002_auto_20160305_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=64, null=True)),
                ('city', models.CharField(max_length=25, null=True)),
                ('post_code', models.CharField(max_length=8)),
                ('county', models.CharField(max_length=25, null=True)),
                ('district', models.CharField(max_length=25, null=True)),
                ('city_district', models.CharField(max_length=25, null=True)),
                ('country', models.CharField(max_length=25, null=True)),
                ('primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deletion_date', models.DateTimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iupdsmanager.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='deletion_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='emailtrack',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
