# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iupdsmanager', '0002_auto_20160409_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='appscale_user_id',
            field=models.CharField(default=3456789045465465475757L, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
