# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import iupdsmanager.generators


class Migration(migrations.Migration):

    dependencies = [
        ('iupdsmanager', '0003_profile_appscale_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='client_id',
            field=models.CharField(db_index=True, default=iupdsmanager.generators.generate_client_id, max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='client_secret',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
