# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iupdsmanager', '0004_auto_20160305_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_section',
            field=models.CharField(choices=[('HOME', 'Home'), ('OFFICE', 'Offcice'), ('MOBILE', 'Mobile')], max_length=15, null=True),
        ),
    ]
