# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iupdsmanager', '0005_contact_contact_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_section',
            field=models.CharField(choices=[('PHONE', 'Phone'), ('FAX', 'Fax'), ('EMAIL', 'Email'), ('WWW', 'www'), ('SKYPE', 'Skype'), ('SKYPE_NO', 'Skype_no'), ('BLOG', 'Blog'), ('OTHER', 'Other')], default='OTHER', max_length=15),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('HOME', 'Home'), ('OFFICE', 'Offcice'), ('MOBILE', 'Mobile')], max_length=15, null=True),
        ),
    ]
