# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import iupdsmanager.generators


class Migration(migrations.Migration):

    dependencies = [
        ('iupdsmanager', '0005_auto_20160504_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.AlterField(
            model_name='application',
            name='client_id',
            field=models.CharField(db_index=True, default=iupdsmanager.generators.generate_client_id, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='client_secret',
            field=models.CharField(blank=True, db_index=True, default=iupdsmanager.generators.generate_client_secret, max_length=255),
        ),
    ]
