# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iupdsmanager', '0006_auto_20160305_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('HOME', 'Home'), ('OFFICE', 'Offcice'), ('MOBILE', 'Mobile'), ('VOICE', 'Voice')], max_length=15, null=True),
        ),
    ]
