# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iupdsmanager', '0007_auto_20160305_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='deletion_date',
            field=models.DateTimeField(null=True),
        ),
    ]
