FORMAT: 1A
HOST: http://iupds.ee/

# IUPDS

API description for request and response examples for pds 

## Emails [/{user_id}/emails]

### Get Personal Emails [GET]

+ Response 200 (application/json)

        {
            format: "linked-data-api",
            version: "1.0",
            result: {
                _about: "http://inforegister.ee/185804764220139124118/emails",
                definition: "http://inforegister.ee/meta/user_id/_emails.json",
                extendedMetadataVersion: "http://inforegister.ee/185804764220139124118/email.json?_metadata=all",
                first: "http://inforegister.ee/185804764220139124118/email.json?_page=0",
                hasPart: "http://inforegister.ee/185804764220139124118/email.json",
                isPartOf: "http://inforegister.ee/185804764220139124118/email.json"
                items: [
                    {
                    _about: "https://graph.ir.ee/emails/artur-eginvest-ee",
                    hasValue: "mailto:artur@eginvest.ee",
                    type: "http://www.w3.org/2006/vcard/ns#Work"
                    },
                    {
                    _about: "https://graph.ir.ee/emails/info-eg-ee",
                    hasValue: "mailto:info@eg.ee",
                    type: "http://www.w3.org/2006/vcard/ns#Work"
                    },
                    {
                    _about: "https://graph.ir.ee/emails/urmas-eg-ee",
                    hasValue: "mailto:urmas@eg.ee",
                    type: "http://www.w3.org/2006/vcard/ns#Work"
                    },
                    {
                    _about: "https://graph.ir.ee/emails/vedu-eg-ee",
                    hasValue: "mailto:vedu@eg.ee",
                    type: "http://www.w3.org/2006/vcard/ns#Work"
                    }
                ],
                itemsPerPage: 50,
                page: 0,
                startIndex: 1,
                totalResults: 2,
                type: [
                    "http://purl.org/linked-data/api/vocab#ListEndpoint",
                    "http://purl.org/linked-data/api/vocab#Page"
                ]
            }
        }